#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""make_stub_bats.py -- relocation-proof .bat wrappers for Scripts\\*.exe.

pip's console/GUI entry-point exes (distlib stubs) embed the ABSOLUTE path
of the python.exe that was present at install time.  Move the tree to
another machine/path and every stub breaks.  This tool parses each stub's
appended zip (distlib format), extracts the entry call, and writes a
sibling .bat that resolves python.exe RELATIVE to itself:

    @echo off
    "%~dp0..\\python.exe" -c "import sys; from pkg import main as _f; sys.exit(_f())" %*

GUI stubs (subsystem=WINDOWS, e.g. idle) get pythonw.exe and no console
boilerplate.  Files that are not distlib stubs are skipped.

Usage:
    python make_stub_bats.py [TREE]     # default: sibling Python314 tree
    python make_stub_bats.py --scripts-dir D:\\path\\Scripts [--dry-run]
"""
import argparse
import io
import os
import re
import sys
import zipfile

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "src"))

# A patched tree's interpreter preloads pywin7gate (sitecustomize audit
# hook) from its own Lib\; evict it so this checkout's code is used.
for _m in [m for m in list(sys.modules)
           if m == "pywin7gate" or m.startswith("pywin7gate.")]:
    del sys.modules[_m]
from pywin7gate import pe as pemod                            # noqa: E402

ENTRY_RE = re.compile(r"^\s*from\s+([\w\.]+)\s+import\s+([\w\.]+)",
                      re.MULTILINE)


def parse_stub(exe_path):
    """Return (module, func, is_gui) for a distlib stub exe, else None."""
    try:
        with open(exe_path, "rb") as f:
            data = f.read()
    except OSError:
        return None
    if b"PK\x05\x06" not in data:
        return None
    try:
        zf = zipfile.ZipFile(io.BytesIO(data))
        names = zf.namelist()
        main_name = "__main__.py" if "__main__.py" in names else None
        if not main_name:
            return None
        main_py = zf.read(main_name).decode("utf-8", "replace")
    except (zipfile.BadZipFile, KeyError, OSError):
        return None
    m = ENTRY_RE.search(main_py)
    if not m:
        return None
    is_gui = False
    try:
        pe = pemod.PEFile(exe_path)
        is_gui = pe.subsystem == 2
    except pemod.PEError:
        pass
    return m.group(1), m.group(2), is_gui


BAT_TMPL = """@echo off
rem relocation-proof wrapper generated by make_stub_bats.py
rem (original: {exe_name}; entry: {module}:{func})
"%~dp0..\\{py_exe}" -c "import sys; from {module} import {func} as _entry; sys.exit(_entry())" %*
"""

BAT_TMPL_GUI = """@echo off
rem relocation-proof wrapper generated by make_stub_bats.py
rem (original: {exe_name}; entry: {module}:{func}; GUI subsystem)
start "" "%~dp0..\\{py_exe}" -c "import sys; from {module} import {func} as _entry; sys.exit(_entry())" %*
"""


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("tree", nargs="?",
                    default=os.path.normpath(os.path.join(
                        HERE, "..", "..", "..", "Python", "Python314")))
    ap.add_argument("--scripts-dir", default=None)
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args(argv)

    scripts = args.scripts_dir or os.path.join(args.tree, "Scripts")
    if not os.path.isdir(scripts):
        print("error: no Scripts dir: " + scripts, file=sys.stderr)
        return 2

    made = skipped = failed = 0
    for fn in sorted(os.listdir(scripts)):
        if not fn.lower().endswith(".exe"):
            continue
        exe = os.path.join(scripts, fn)
        info = parse_stub(exe)
        if not info:
            skipped += 1
            continue
        module, func, is_gui = info
        bat = exe[:-4] + ".bat"
        body = (BAT_TMPL_GUI if is_gui else BAT_TMPL).format(
            exe_name=fn, module=module, func=func,
            py_exe="pythonw.exe" if is_gui else "python.exe")
        if args.dry_run:
            print("would write: %s (%s:%s%s)" %
                  (os.path.basename(bat), module, func,
                   ", gui" if is_gui else ""))
            made += 1
            continue
        try:
            with open(bat, "w", encoding="ascii", newline="\r\n") as f:
                f.write(body)
            print("wrote: %s -> %s:%s%s" %
                  (os.path.basename(bat), module, func,
                   ", gui" if is_gui else ""))
            made += 1
        except OSError as e:
            print("FAILED %s: %s" % (bat, e), file=sys.stderr)
            failed += 1
    print("done: %d written, %d skipped (not stubs), %d failed" %
          (made, skipped, failed))
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
